config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  resources :records
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
   root "welcome#index"
   get '/about/', to: 'welcome#about';
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/record.rb
class Record < ApplicationRecord
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,:trackable, :validatable, :omniauthable, omniauth_providers: [:github, :google_oauth2]

  def self.from_omniauth(access_token)
    
    user = User.where(email: access_token.info.email).first       
    # Uncomment the section below if you want users to be created if they don't exist
    unless user
      user = User.create(
        email: access_token.info.email,
        password: Devise.friendly_token[0,20]
      )
    end
    user.name = access_token.info.email
    user.image = access_token.info.image
    user.uid = access_token.uid
    user.provider = access_token.provider
    user.save 

    user
  end


  enum :role, { normal_user: 0, admin: 1 }
  
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_back(fallback_location: root_path)
  end

  helper_method :admin?
  
  helper_method :normal_user?
  def admin?
    current_user && current_user.role == "admin"
  end
  
  def normal_user?
    current_user && current_user.role == "normal_user"
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
 
    def index
        
       @record = Record.all
       
       @q=Record.ransack(params[:q])

       @records = @q.result(distinct: true)
       authorize @record
    end

    def new
       @record = Record.new
    end

    def create
    
    @record = Record.new(params.require(:record).permit(:name,:address,:age))
    authorize @record
       if @record.save 
            
           flash[:success] = "You have successfully entered your details"
           redirect_to root_path
       else
           render 'new'
       end
   end

   def show
       @record = Record.find(params[:id])
       @user=User.find(params[:id])
       
   end

   def edit
        @record = Record.find(params[:id])
   end
    
   def update
        @record = Record.find(params[:id])
        authorize @record
       if @record.update(params.require(:record).permit(:name,:address,:age))
        
           flash[:success] = "You have successfully updated your information"
           redirect_to records_path(@record)
       else
           render 'new'
       end
   end

   def destroy
        @record = Record.find(params[:id])
       @record.destroy
       redirect_to records_path
   end

   

end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    handle_auth "Google"
  end

  def github
    handle_auth "Github"
  end

    def handle_auth(kind)
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env['omniauth.auth'])
  
        if @user.persisted?
          flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: kind
          sign_in_and_redirect @user, event: :authentication
        else
          session['devise.auth_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
          redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
        end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index
    end

    def about 
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg " style="background-color: blue;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" <%= link_to "Home", root_path %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" <%= link_to "About", about_path %></a>
        </li>
        
        
        <% if admin? %>
              <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %>
              <span class="badge bg-success"> <%= current_user.role  %> </span>
              </a>
              <ul class="dropdown-menu">
                <li><a class="nav-link active text-black" aria-current="page" <%=link_to "All Records", records_path %></a></li>
                <li><a class="nav-link active text-black" aria-current="page" <%=link_to "New Entry", new_record_path %></a></li>
              </ul>  
            
              <%  elsif normal_user? %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= current_user.email %>
                  <span class="badge bg-success"> <%= current_user.role  %> </span>
                </a>
                <ul class="dropdown-menu">
                <li><a class="nav-link active text-black" aria-current="page" <%=link_to "All Records", records_path %></a></li>
                <li><a class="nav-link active text-black" aria-current="page" <%=link_to "New Entry", new_record_path %></a></li>
              </ul> 
              <% end %>
      </ul>
      <div class="navbar-end">
            <div class="navbar-item">
            <div class="buttons">
            <% if user_signed_in? %> 
              <%= current_user.name %>
              <%= image_tag current_user.image, size: "30*30" if current_user.image? %> 
              <%= current_user.uid %>
              <%= current_user.provider %>   
              <%= link_to "Log Out" , destroy_user_session_path(@user), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-success"  %> </a>
            <%else%>  
              <%= link_to "sign in with github", omniauth_authorize_path(User, :github), method: :post, data: { disable_with: "connecting....."} %>  
              <%= link_to "Sign up",  new_user_registration_path(@user), class: "btn btn-success" %>
              <%= link_to "Log in",  new_user_session_path(@user), class: "btn btn-success" %>
            <%end%>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoPundit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
  
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/records/_search.html.erb
<%= search_form_for @q, url: :records do |form| %>
  <div class="container d-flex">
    <div class="form-group mt-3" >
      <strong><%= form.label :search_by_Name %></strong>
      <%= form.search_field :name_cont %>
    </div>
    <div class="form-group mt-3" >
      <strong><%= form.label :search_By_id_number %></strong>
      <%= form.search_field :id_eq %>
    </div>
    <div class="form-group mt-3" >
      <strong><%= form.label :search_By_address %></strong>
      <%= form.search_field :address_cont %>
    </div>
    <div class="form-group mt-3">
      <%= form.submit 'search record', class: "btn btn-warning btn-lg" %>
      
    </div>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1 style="text-align:center;color:white;background-color:red">Edit Record Detail</h1>

<%= form_with model: @record do |f| %>
  <div class="container-sm">
    
  
    <div class="row mb-3 mt-5">
    
      <strong><%= f.label :enter_name %></strong>
      <%= f.text_field :name, placeholder: "Enter Author Name", autofocus: true %>
    
    </div>

    <div class="row mb-3">
      <strong><%= f.label :address %></strong>
      <%= f.text_field :address, placeholder: "Enter about Author", autofocus: true %>
    
    </div>

    

  <%= f.submit "submit" %>
  </div>

  
  
<%end%>

app/views/records/index.html.erb
<h1 style="text-align:center;color:white;background-color:red">All Record Detail</h1>

<%= render 'records/search' %>



<table class="table">
  <thead>
    <tr>
      <th scope="col">Serial Number</th>
      <th scope="col">Name</th>
      
      <th scope="col">Date Of Birth</th>
      <th scope="col">Address</th>
      
      <th scope="col">Action</th>

    </tr>
  </thead>
  <tbody>
  <% @records.each do |record| %>
    <tr>
      <th scope="row"><%= record.id %></th>
      <td><%= record.name %></td>
      
      <td><%= record.age %></td>
      <td><%= record.address %></td>
     
      
      <td><%= link_to 'More info', record_path(record) %></td>
      
       
    </tr>
    <% end %>
    
  </tbody>
</table>

app/views/records/new.html.erb
<h1 style="text-align:center;color:white;background-color:red">Enter Record Detail</h1>

<%= form_with model: @record do |f| %>
  <div class="container-sm">
    
  
    <div class="row mb-3 mt-5">
    
      <strong><%= f.label :enter_name %></strong>
      <%= f.text_field :name, placeholder: "Enter Author Name", autofocus: true %>
    
    </div>

    <div class="row mb-3">
      <strong><%= f.label :address %></strong>
      <%= f.text_field :address, placeholder: "Enter about Author", autofocus: true %>
    
    </div>

    <div class="column mb-3">
      <strong><%= f.label :enter_date_of_birth %></strong>
      <%= f.date_field :age %>
    
    </div>

  <%= f.submit "submit" %>
  </div>

  
  
<%end%>

app/views/records/show.html.erb
<h1 style="text-align:center;color:white;background-color:red"> Personal Detail Detail</h1>

<div class="container">
  <div class="row">
    <div class="col-9"><h2 style="text-align:left;color:blue"> Information</h2></div><hr>
    
    
    
    <div class="col-6 ">
    <br><h2 >Name :- <%= @record.name %></h2>
    
    <br><h2 >Date Of Birth :- <%= @record.age %></h2>
    
    <br><h2 >Address :- <%= @record.address %></h2>
    <br><h2 >Created Time :- <%= @record.created_at %></h2>
    <br><h2 >Role :- <%= @user.role %></h2>
    
    
    
    </div>
    </div>
    
  </div>

  <%= link_to 'Edit Profile', edit_record_path(@record), class: "btn btn-warning" %>
  
  

app/views/welcome/about.html.erb
<h1>This is about page</h1>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<p>you can see the record after clicking search button </p>